TFP-4124 Endring Manuell Journalføring
navikt/fpfordel pull request #2229
Opened 2023-03-01 11:15 UTC by AnjaAalerud

Lagt inn nye verdier, og endret eksisterende felter på SakInfoDto. Bruker samme SakInfoDto til front end for ferdigstillJournalpost.

2023-03-01 11:27 UTC, jolarsen commented on domene/src/main/java/no/nav/foreldrepenger/mottak/klient/FamilieHendelseTypeDto.java
> +    ADOPSJON("ADPSJN"),
Kan du ikke bruke en plain enum? Hva trenger du disse "KODE"ene til?

2023-03-01 11:33 UTC, mrsladek commented on domene/src/main/java/no/nav/foreldrepenger/mottak/klient/FamilieHendelseTypeDto.java
> +    ADOPSJON("ADPSJN"),
Må nesten høre med @pekern og om det finnes noe tilsvarende i frontend allerede. 
Om det ikke finnes noe tilsvarende fra før så er det faktisk bedre med en plain enum.

2023-03-01 11:34 UTC, jolarsen requested changes
Jeg synes vi skal lage kontrakts-enumer med en gang.
Vi bør unngå å eksportere interne domenekoder fra Fpsak. 
Det går på vedlikeholdbarhet

2023-03-01 11:34 UTC, pekern commented on domene/src/main/java/no/nav/foreldrepenger/mottak/klient/FamilieHendelseTypeDto.java
> +    ADOPSJON("ADPSJN"),
https://github.com/navikt/fp-frontend/blob/master/packages/kodeverk/src/familieHendelseType.ts denne ligger allerede i frontend i alle fall

2023-03-01 11:39 UTC, jolarsen commented on domene/src/main/java/no/nav/foreldrepenger/mottak/klient/FamilieHendelseTypeDto.java
> +    ADOPSJON("ADPSJN"),
Her må vi skille mellom kontrakt fp-frontend vs fpfordel og fpfordel vs fpsak.
Jeg synes fpfordel <-> fpsak bør bruke plain enums.
Så får fpfordel bruke et kodeverk som fp-frontend forstår (må serialisere "kode") ut fra fpfordel.

2023-03-02 12:17 UTC, AnjaAalerud commented on domene/src/main/java/no/nav/foreldrepenger/mottak/klient/FamilieHendelseTypeDto.java
> +    ADOPSJON("ADPSJN"),
Har oppdatert slik at vi har plain enums mellom fpsak-fordel, og mapper riktig verdi til frontend

2023-03-03 09:48 UTC, merged