Ny felles og ny konvensjon for skjermet
navikt/fpfordel pull request #2336
Opened 2023-06-27 08:05 UTC by jolarsen

2023-06-27 11:07 UTC, palfi commented
jeg tror vi kan fjerne bruk av lagStatusURI, begge steder.
Den eneste redirecten vi trenger er i svaret til POST /dokumentforsendelse. Denne må redirecte til /status.
Svaret i /status trenger ikke å redirecte til noe.
Mottak poller mot /status status x ganger så lenge response body har status "PENDING"

2023-06-27 11:08 UTC, espenwaaga approved these changes

2023-06-27 11:08 UTC, palfi requested changes
se kommentar

2023-06-27 11:16 UTC, espenwaaga commented
> jeg tror vi kan fjerne bruk av lagStatusURI, begge steder.
> Den eneste redirecten vi trenger er i svaret til POST /dokumentforsendelse. Denne må redirecte til /status.
> Svaret i /status trenger ikke å redirecte til noe.
> Mottak poller mot /status x ganger så lenge response body har status "PENDING"

Enig. Fpsoknad-mottak tar bare å sjekker bodyen. Hvis den er av typen PendingKvittering (forsendelseStatus = PENDING). Så tar vi å retryer opp til 10 ganger.

2023-06-27 11:58 UTC, jolarsen commented
Nei, men det sjekkes på at det sendes en Respons.seeOther(URI uri) - den vil gjerne ha en URI :-)

2023-06-27 12:01 UTC, palfi commented
> Nei, men det sjekkes på at det sendes en Respons.seeOther(URI uri) - den vil gjerne ha en URI :-)

tror ikke mottak bryr seg om http status code

2023-06-27 12:02 UTC, jolarsen commented
@espenwaaga skrev ikke du at mottak så på statuskode ?

2023-06-27 12:04 UTC, jolarsen commented
Dvs kan vi svare Response.ok(forsendelseStatusDto) for både tilfelle FPSAK og GOSYS?

2023-06-27 12:08 UTC, espenwaaga commented
> Dvs kan vi svare Response.ok(forsendelseStatusDto) for både tilfelle FPSAK og GOSYS?

Ja. Og ved PENDING trenger vi location header

2023-06-27 12:20 UTC, palfi commented on web/src/main/java/no/nav/foreldrepenger/fordel/web/app/rest/DokumentforsendelseRestTjeneste.java
> +            return Response.ok().entity(forsendelseStatusDto).build();
fjerne if? Ser litt kleint ut nå

2023-06-27 12:40 UTC, jolarsen commented
@palfi oppdatert

2023-06-27 12:42 UTC, palfi commented
> @palfi oppdatert

good to go, bortsatt at 
![image](https://github.com/navikt/fpfordel/assets/1370608/cc10700f-d261-435d-b00e-f10642181461)
kan vel slås sammen

2023-06-27 13:01 UTC, jolarsen commented
@palfi done

2023-06-28 07:27 UTC, palfi approved these changes

2023-06-28 09:25 UTC, merged