Legger til støtte for å motta og journalføre vedlegg av typen pdf, pn…
navikt/fpfordel pull request #2365
Opened 2023-08-24 08:00 UTC by espenwaaga

…g og jpg fra selvbetjening

2023-08-24 08:02 UTC, palfi approved these changes

2023-08-24 11:01 UTC, jolarsen approved these changes
Ser OK ut. Enn så lenge får vi vente litt på at Ida får folk til å bli enige med oss.

2023-08-24 11:20 UTC, espenwaaga commented
@jolarsen Tenkte å vente. Kan eventuelt merge endringene opp til foreldrepengesokand-api der hvor vi konverterer til PDF. Vi vil da uansett bare få PDF ned over som før.

2023-09-18 17:03 UTC, mrsladek requested changes
Vi bør diskutere dette en gang til - Drammen mener at de ikke lenger får en mulighet å rotere dokumenter i løsningen om det ikke journalføres som PDF.

2024-09-25 09:16 UTC, closed without merging